# Generated by Django 4.2.1 on 2023-05-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='rejcted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
