# Generated by Django 4.2.1 on 2023-05-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bug_rejcted_bug_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
