# Generated by Django 4.2.1 on 2023-05-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bug_bug_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='rejcted',
            new_name='rejected',
        ),
    ]
